// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxQZHI8LY3a_OffH2SrvRbQdJWpjCFgzs',
    appId: '1:624423629498:web:4db7378992bbfb16a2c883',
    messagingSenderId: '624423629498',
    projectId: 'news-app-39489',
    authDomain: 'news-app-39489.firebaseapp.com',
    storageBucket: 'news-app-39489.appspot.com',
    measurementId: 'G-QSHSM33GC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_TyBfjKlf9RGIytMRuSxRzUYbgW4tOS0',
    appId: '1:624423629498:android:7211607b8fb62754a2c883',
    messagingSenderId: '624423629498',
    projectId: 'news-app-39489',
    storageBucket: 'news-app-39489.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyLo58W_LOzjSb1ttq5Oq6_bYiRW2Gahk',
    appId: '1:624423629498:ios:a26ceba82313c880a2c883',
    messagingSenderId: '624423629498',
    projectId: 'news-app-39489',
    storageBucket: 'news-app-39489.appspot.com',
    iosBundleId: 'com.esmatullah.newsApp',
  );
}
